CREATE TABLE [dbo].[tblBudgetAllocation] (
    [countryID]              INT           NULL,
    [balBudgetOwnerName]     NVARCHAR (50) NULL,
    [cusGroup1ID]            INT           NULL,
    [cusGroup2ID]            INT           NULL,
    [cusGroup3ID]            INT           NULL,
    [cusGroup4ID]            INT           NULL,
    [cusGroup5ID]            INT           NULL,
    [cusGroup6ID]            INT           NULL,
    [cusGroup7ID]            INT           NULL,
    [cusGroup8ID]            INT           NULL,
    [secGroup1ID]            INT           NULL,
    [secGroup2ID]            INT           NULL,
    [secGroup3ID]            INT           NULL,
    [secGroup4ID]            INT           NULL,
    [secGroup5ID]            INT           NULL,
    [secGroup6ID]            INT           NULL,
    [balYear]                INT           NULL,
    [balBudgetNr]            INT           NULL,
    [balTotalTradeSpendPerc] FLOAT (53)    NULL,
    [balListFee]             FLOAT (53)    NULL,
    [balCDF]                 FLOAT (53)    NULL,
    [balFixedTT]             FLOAT (53)    NULL,
    [balFixedTTGL]           FLOAT (53)    NULL,
    [balFixedTTGLTwo]        FLOAT (53)    NULL,
    [ConRebF]                FLOAT (53)    NULL,
    [DistTargetF]            FLOAT (53)    NULL,
    [LightF]                 FLOAT (53)    NULL,
    [CdisDistDevF]           FLOAT (53)    NULL,
    [DispMtF]                FLOAT (53)    NULL,
    [SpaceBuyGtF]            FLOAT (53)    NULL,
    [ComAssortF]             FLOAT (53)    NULL,
    [CatManF]                FLOAT (53)    NULL,
    [AnnivF]                 FLOAT (53)    NULL,
    [TprF]                   FLOAT (53)    NULL,
    [EdlpDiscountF]          FLOAT (53)    NULL,
    [FeatureCostF]           FLOAT (53)    NULL,
    [LocPromoF]              FLOAT (53)    NULL,
    [MailAdvF]               FLOAT (53)    NULL,
    [UnconRebateF]           FLOAT (53)    NULL,
    [UllagesF]               FLOAT (53)    NULL,
    [NewStoreF]              FLOAT (53)    NULL,
    [DcAllowF]               FLOAT (53)    NULL,
    [importlogID]            INT           NOT NULL
);

