CREATE TABLE [dbo].[tblFixedTradeTermPercentages] (
    [countryID]          INT           NOT NULL,
    [fftYear]            INT           NOT NULL,
    [fftBudgetOwnerName] NVARCHAR (50) NULL,
    [CusGroup5ID]        INT           NULL,
    [CusGroup6ID]        INT           NULL,
    [secGroup2ID]        INT           NULL,
    [fftBudgetNr]        INT           NULL,
    [ConRebF]            FLOAT (53)    NULL,
    [DistTargetF]        FLOAT (53)    NULL,
    [LightF]             FLOAT (53)    NULL,
    [CdisDistDevF]       FLOAT (53)    NULL,
    [DispMtF]            FLOAT (53)    NULL,
    [SpaceBuyGtF]        FLOAT (53)    NULL,
    [ComAssortF]         FLOAT (53)    NULL,
    [CatManF]            FLOAT (53)    NULL,
    [AnnivF]             FLOAT (53)    NULL,
    [TprF]               FLOAT (53)    NULL,
    [EdlpDiscountF]      FLOAT (53)    NULL,
    [FeatureCostF]       FLOAT (53)    NULL,
    [LocPromoF]          FLOAT (53)    NULL,
    [MailAdvF]           FLOAT (53)    NULL,
    [UnconRebateF]       FLOAT (53)    NULL,
    [UllagesF]           FLOAT (53)    NULL,
    [NewStoreF]          FLOAT (53)    NULL,
    [DcAllowF]           FLOAT (53)    NULL,
    [importlogID]        INT           NOT NULL
);

