CREATE TABLE [dbo].[tblPromotionDetailsIncentive] (
    [PromotionDetailsIncentiveID] INT           IDENTITY (1, 1) NOT NULL,
    [promotionTypeID]             INT           NOT NULL,
    [promotionID]                 INT           NOT NULL,
    [SecondaryCustomerID]         INT           NULL,
    [ProductID]                   INT           NULL,
    [detProductField]             NVARCHAR (50) NULL,
    [detProductValue]             INT           NULL,
    [detTargetType]               NVARCHAR (50) NULL,
    [detNonSalesTarget]           NVARCHAR (50) NULL,
    [detNumberOfTiers]            INT           NULL,
    [detIncentiveTier]            INT           NULL,
    [detGrowthTargetPercentage]   FLOAT (53)    NULL,
    [detGrowthTarget]             FLOAT (53)    NULL,
    [detTargetPercentage]         FLOAT (53)    NULL,
    [detPayoutPercentage]         FLOAT (53)    NULL,
    [detPayout]                   FLOAT (53)    NULL,
    [detVolumeReqRetailer]        FLOAT (53)    NULL,
    [detVolumeReqUnit]            FLOAT (53)    NULL,
    [detMaximumPayoutPercentage]  FLOAT (53)    NULL,
    [detNumberOfDisplays]         INT           NULL,
    [DisplayFee]                  FLOAT (53)    NULL,
    [detRebatePerc]               FLOAT (53)    NULL,
    [detFreeGoodsAmount]          FLOAT (53)    NULL,
    [detFreeGoodsunit]            FLOAT (53)    NULL,
    [detValue]                    FLOAT (53)    NULL,
    [detUnit]                     INT           NULL,
    [detVolumeReq]                INT           NULL,
    [detRebate]                   FLOAT (53)    NULL,
    [detFreegoodscap]             INT           NULL,
    [detSaleTarget]               FLOAT (53)    NULL,
    [detDisplayRebatePercentage]  FLOAT (53)    NULL,
    [detOutletClass]              FLOAT (53)    NULL,
    CONSTRAINT [tblPromotionDetailsIncentive_pk] PRIMARY KEY CLUSTERED ([PromotionDetailsIncentiveID] ASC)
);

