CREATE TABLE [dbo].[tblPromotionDetails] (
    [PromotionDetailsID]            INT           IDENTITY (1, 1) NOT NULL,
    [countryID]                     INT           NOT NULL,
    [PromotionID]                   INT           NOT NULL,
    [PromotionTypeID]               INT           NOT NULL,
    [detPrdProductField]            NVARCHAR (20) NULL,
    [detPrdProductValue]            INT           NULL,
    [productID]                     INT           NULL,
    [detStepNr]                     INT           NULL,
    [detGroupNr]                    INT           NULL,
    [detPercentageOfBudget]         INT           NULL,
    [detProductClientCode]          INT           NULL,
    [detVolumeReq]                  INT           NULL,
    [detVolumeReqTargetIncentive]   INT           NULL,
    [detRebate]                     FLOAT (53)    NULL,
    [detRebatepercentage]           FLOAT (53)    NULL,
    [detRebateLumpsum]              FLOAT (53)    NULL,
    [detTradediscount]              FLOAT (53)    NULL,
    [detTradediscountPercentage]    FLOAT (53)    NULL,
    [detConsumerDiscount]           FLOAT (53)    NULL,
    [detConsumerDiscountPercentage] FLOAT (53)    NULL,
    [detCustomerpoints]             INT           NULL,
    [detCustomerpointsrequirement]  INT           NULL,
    [detPremiumCost]                FLOAT (53)    NULL,
    [detPremiumQuantity]            INT           NULL,
    [detSpaceBuyFee]                FLOAT (53)    NULL,
    [detShelfSpaceFee]              FLOAT (53)    NULL,
    [detGondolaFee]                 FLOAT (53)    NULL,
    [detDisplayFee]                 FLOAT (53)    NULL,
    [detDisplayNumber]              INT           NULL,
    [detNumberofFreeUOMs]           INT           NULL,
    [detFreeUOM]                    INT           NULL,
    [detAgencyfees]                 FLOAT (53)    NULL,
    [detFreegoodsamount]            INT           NULL,
    [detFreegoodsunit]              INT           NULL,
    [detFreegoodscap]               INT           NULL,
    [detStoreRevampingAmount]       FLOAT (53)    NULL,
    [detNewStoreOpeningAmount]      FLOAT (53)    NULL,
    [detListingFeeAmount]           FLOAT (53)    NULL,
    [detAnniversarySponsorAmount]   FLOAT (53)    NULL,
    [detScanDataLightboxAmount]     FLOAT (53)    NULL,
    [detIncentiveAmount]            FLOAT (53)    NULL,
    [detLocPromoLumpSum]            FLOAT (53)    NULL,
    [detDiscountInvoice]            FLOAT (53)    NULL,
    [detCTNFrom]                    FLOAT (53)    NULL,
    [detDCTNTo]                     FLOAT (53)    NULL,
    [detNTT]                        FLOAT (53)    NULL,
    [detInvoiceDiscount]            FLOAT (53)    NULL,
    [detPromotionAmount]            FLOAT (53)    NULL,
    [detMailcost]                   FLOAT (53)    NULL,
    [detPOSMaterialcost]            FLOAT (53)    NULL,
    [detOutlet]                     INT           NULL,
    [detOutletClass]                INT           NULL,
    [detTargetType]                 INT           NULL,
    [detIncentiveTier]              INT           NULL,
    [detGrowthTargetPercentage]     FLOAT (53)    NULL,
    [detGrowthTarget]               FLOAT (53)    NULL,
    [detPayoutPercentage]           FLOAT (53)    NULL,
    [detPayout]                     FLOAT (53)    NULL,
    [detNonSalesTarget]             NVARCHAR (50) NULL,
    [detCappedAmount]               FLOAT (53)    NULL,
    [detFreegoodscapunit]           INT           NULL,
    [detPrintingAndStickering]      FLOAT (53)    NULL,
    [detDisplayAnP]                 FLOAT (53)    NULL,
    [detVoucher]                    FLOAT (53)    NULL,
    [detAgencyCosts]                FLOAT (53)    NULL,
    [detLuckyDraw]                  FLOAT (53)    NULL,
    [detLocalisedRebate]            FLOAT (53)    NULL,
    [detLocalisedRebatepercentage]  FLOAT (53)    NULL,
    [detLocalisedRebateLumpsum]     FLOAT (53)    NULL,
    [detPremiumMechanic]            FLOAT (53)    NULL,
    CONSTRAINT [tblPromotionDetails_pk] PRIMARY KEY CLUSTERED ([PromotionDetailsID] ASC)
);

