CREATE TABLE [dbo].[tblPromotion] (
    [promotionID]             INT            IDENTITY (1, 1) NOT NULL,
    [countryID]               INT            NOT NULL,
    [prmPromotionClientCode]  NVARCHAR (20)  NULL,
    [prmPromotionName]        NVARCHAR (150) NULL,
    [prmPromotionDescription] NTEXT          NULL,
    [promotionTypeID]         INT            CONSTRAINT [DF_tblPromotion_promotionTypeID] DEFAULT ((0)) NULL,
    [prmPromotionStructure]   NVARCHAR (20)  NULL,
    [prmParentSelectionID]    INT            CONSTRAINT [DF_tblPromotion_prmParentSelectionID] DEFAULT ((0)) NULL,
    [ObjectiveID]             INT            CONSTRAINT [DF_tblPromotion_ObjectiveID] DEFAULT ((0)) NULL,
    [ActivityID]              INT            CONSTRAINT [DF_tblPromotion_ActivityID] DEFAULT ((0)) NULL,
    [ActivityTwoID]           INT            CONSTRAINT [DF_tblPromotion_ActivityTwoID] DEFAULT ((0)) NULL,
    [prmSupport]              NVARCHAR (20)  CONSTRAINT [DF_tblPromotion_prmSupport] DEFAULT ('0') NULL,
    [prmInvoice]              INT            NULL,
    [prmStatusID]             INT            CONSTRAINT [DF_tblPromotion_prmStatusID] DEFAULT ((0)) NULL,
    [prmUnitID]               INT            CONSTRAINT [DF_tblPromotion_prmUnitID] DEFAULT ((0)) NULL,
    [prmBudgetOwnerID]        INT            CONSTRAINT [DF_tblPromotion_prmBudgetOwnerID] DEFAULT ((0)) NULL,
    [isActive]                INT            NULL,
    [prmIOnumber]             INT            NULL,
    [prmDateStart]            DATETIME       NULL,
    [prmDateEnd]              DATETIME       NULL,
    [prmDateFirstOrder]       DATETIME       NULL,
    [prmDateLastOrder]        DATETIME       NULL,
    [prmCreator]              INT            NULL,
    [prmProductfield]         NVARCHAR (20)  NULL,
    [prmCustomerfield]        NVARCHAR (20)  NULL,
    [prmDateCreated]          DATETIME       CONSTRAINT [DF_tblPromotion_prmDateCreated] DEFAULT (getdate()) NULL,
    [prmDateSubmitted]        DATETIME       NULL,
    [prmDateApproved]         DATETIME       NULL,
    [prmDateActualStart]      DATETIME       NULL,
    [prmDateActualEnd]        DATETIME       NULL,
    [prmBudgetNr]             INT            NULL,
    [prmGrossSales]           FLOAT (53)     NULL,
    [prmTotalExpenses]        FLOAT (53)     NULL,
    [prmGP]                   FLOAT (53)     NULL,
    [prmGPPerc]               FLOAT (53)     NULL,
    [prmProductGrouping]      NVARCHAR (20)  CONSTRAINT [DF_tblPromotion_prmProductGrouping] DEFAULT ('0') NULL,
    [prmSelectedProductGroup] INT            CONSTRAINT [DF_tblPromotion_prmSelectedProductGroup] DEFAULT ((0)) NULL,
    [prmListingFees]          FLOAT (53)     NULL,
    [isDeleted]               INT            CONSTRAINT [DF_tblPromotion_isDeleted] DEFAULT ((0)) NULL,
    [prmOriginalPromotionID]  INT            NULL,
    [prmNFObjPri]             INT            CONSTRAINT [DF_tblPromotion_prmNFObjPri] DEFAULT ((0)) NULL,
    [prmNFObjSec]             INT            CONSTRAINT [DF_tblPromotion_prmNFObjSec] DEFAULT ((0)) NULL,
    [prmNFObjTri]             NCHAR (10)     CONSTRAINT [DF_tblPromotion_prmNFObjTri] DEFAULT ((0)) NULL,
    [prmCostCenter]           INT            NULL,
    [prmPromotionCategory]    NVARCHAR (50)  NULL,
    [isImported]              BIT            CONSTRAINT [DF_tblPromotion_isImported] DEFAULT ((0)) NULL,
    CONSTRAINT [tblPromotion_pk] PRIMARY KEY CLUSTERED ([promotionID] ASC)
);

