CREATE TABLE [dbo].[tblSecondaryCustomer] (
    [countryID]                      INT            NOT NULL,
    [secondaryCustomerID]            INT            NULL,
    [secSecCusClientCode]            NVARCHAR (100) NOT NULL,
    [customerID]                     INT            NULL,
    [secCustomerClientCode]          INT            NOT NULL,
    [secCustomerName]                NVARCHAR (100) NULL,
    [secSecondaryCustomerClientCode] NVARCHAR (100) NULL,
    [secSecondaryCustomerName]       NVARCHAR (100) NULL,
    [secGroup1ID]                    INT            NULL,
    [secSecGroup1ClientCode]         NVARCHAR (100) NULL,
    [secSecGroup1Desc]               NVARCHAR (100) NULL,
    [secGroup2ID]                    INT            NULL,
    [secSecGroup2ClientCode]         NVARCHAR (100) NULL,
    [secSecGroup2Desc]               NVARCHAR (100) NULL,
    [secGroup3ID]                    INT            NULL,
    [secSecGroup3ClientCode]         NVARCHAR (100) NULL,
    [secSecGroup3Desc]               NVARCHAR (100) NULL,
    [secGroup4ID]                    INT            NULL,
    [secSecGroup4ClientCode]         NVARCHAR (100) NULL,
    [secSecGroup4Desc]               NVARCHAR (100) NULL,
    [secGroup5ID]                    INT            NULL,
    [secSecGroup5ClientCode]         NVARCHAR (100) NULL,
    [secSecGroup5Desc]               NVARCHAR (100) NULL,
    [secGroup6ID]                    INT            NULL,
    [secSecGroup6ClientCode]         NVARCHAR (100) NULL,
    [secSecGroup6Desc]               NVARCHAR (100) NULL,
    [secRegNr]                       NVARCHAR (100) NULL,
    [secFPercentage]                 FLOAT (53)     NULL,
    [validFrom]                      DATETIME       NOT NULL,
    [validTo]                        DATETIME       NOT NULL,
    [importlogID]                    INT            NOT NULL
);

