CREATE TABLE [dbo].[tempBudgetAndForecast] (
    [budBudgetNr]            INT           NOT NULL,
    [countryID]              INT           NOT NULL,
    [budYear]                INT           NOT NULL,
    [monthDate]              INT           NOT NULL,
    [budPrdGroup7Desc]       NVARCHAR (50) NULL,
    [prdGroup7ID]            INT           NULL,
    [budPrdGroup9Desc]       NVARCHAR (50) NULL,
    [prdGroup9ID]            INT           NULL,
    [budParentCode]          NVARCHAR (50) NULL,
    [budCusGroup5Desc]       NVARCHAR (50) NULL,
    [cusGroup5ID]            INT           NULL,
    [budChannel]             VARCHAR (50)  NULL,
    [budCusGroup6Desc]       NVARCHAR (50) NULL,
    [cusGroup6ID]            INT           NULL,
    [budSecGroup2ClientCode] NVARCHAR (50) NULL,
    [secGroup2ID]            INT           NULL,
    [budGrossSales]          FLOAT (53)    NULL,
    [budListingFees]         FLOAT (53)    NULL,
    [budTradeSpend]          FLOAT (53)    NULL,
    [budMarketReturn]        FLOAT (53)    NULL,
    [budNetSales]            FLOAT (53)    NULL,
    [budSAndD]               FLOAT (53)    NULL,
    [budTARO]                FLOAT (53)    NULL,
    [budMaterialCost]        FLOAT (53)    NULL,
    [budProductionCost]      FLOAT (53)    NULL,
    [budVariances]           FLOAT (53)    NULL,
    [budGP]                  FLOAT (53)    NULL,
    [budGPPerc]              FLOAT (53)    NULL,
    [budAAndPPromo]          FLOAT (53)    NULL,
    [importlogID]            INT           NOT NULL
);

