CREATE TABLE [dbo].[tempSystemAccrual] (
    [countryID]               INT            NOT NULL,
    [pnlID]                   INT            NULL,
    [sysPnlAcrCond]           NVARCHAR (100) NOT NULL,
    [customerID]              INT            NULL,
    [sysCustomerClientCode]   INT            NULL,
    [cusGroup1ID]             INT            NULL,
    [sysCusGroup1ClientCode]  NVARCHAR (100) NULL,
    [cusGroup4ID]             INT            NULL,
    [sysCusGroup4ClientCode]  NVARCHAR (100) NULL,
    [cusGroup7ID]             INT            NULL,
    [sysCusGroup7ClientCode]  NVARCHAR (100) NULL,
    [productID]               INT            NULL,
    [sysProductClientCode]    INT            NULL,
    [prdGroup6ID]             INT            NULL,
    [sysPrdGroup6ClientCode]  NVARCHAR (100) NULL,
    [prdGroup11ID]            INT            NULL,
    [sysPrdGroup11ClientCode] NVARCHAR (100) NULL,
    [prdGroup12ID]            INT            NULL,
    [sysPrdGroup12ClientCode] NVARCHAR (100) NULL,
    [sysDocType]              NVARCHAR (100) NULL,
    [sysDelete]               NVARCHAR (100) NULL,
    [sysUomClientCode]        NVARCHAR (100) NULL,
    [sysCurrency]             NVARCHAR (100) NOT NULL,
    [sysAmount]               FLOAT (53)     NOT NULL,
    [combinationID]           INT            NOT NULL,
    [validFrom]               DATETIME       NULL,
    [validTo]                 DATETIME       NULL,
    [importLogID]             INT            NOT NULL,
    [prdGroup1ID]             INT            NULL,
    [prdGroup7ID]             INT            NULL,
    [prdGroup9ID]             INT            NULL,
    [sysPrdGroup1ClientCode]  NVARCHAR (100) NULL,
    [sysPrdGroup7ClientCode]  NVARCHAR (100) NULL,
    [sysPrdGroup9ClientCode]  NVARCHAR (100) NULL
);

