CREATE TABLE [dbo].[tempBudgetAllocation] (
    [countryID]              INT           NOT NULL,
    [balBudgetOwnerName]     NVARCHAR (50) NULL,
    [balCusGroup5Desc]       NVARCHAR (50) NULL,
    [cusGroup5ID]            INT           NULL,
    [balCusGroup6Desc]       NVARCHAR (50) NULL,
    [cusGroup6ID]            INT           NULL,
    [balSecGroup2ClientCode] NVARCHAR (50) NULL,
    [secGroup2ID]            INT           NULL,
    [balYear]                INT           NULL,
    [balBudgetNr]            INT           NULL,
    [balTotalTradeSpendPerc] FLOAT (53)    NULL,
    [ConRebF]                FLOAT (53)    NULL,
    [DistTargetF]            FLOAT (53)    NULL,
    [LightF]                 FLOAT (53)    NULL,
    [CdisDistDevF]           FLOAT (53)    NULL,
    [DispMtF]                FLOAT (53)    NULL,
    [SpaceBuyGtF]            FLOAT (53)    NULL,
    [ComAssortF]             FLOAT (53)    NULL,
    [CatManF]                FLOAT (53)    NULL,
    [AnnivF]                 FLOAT (53)    NULL,
    [TprF]                   FLOAT (53)    NULL,
    [EdlpDiscountF]          FLOAT (53)    NULL,
    [FeatureCostF]           FLOAT (53)    NULL,
    [LocPromoF]              FLOAT (53)    NULL,
    [MailAdvF]               FLOAT (53)    NULL,
    [UnconRebateF]           FLOAT (53)    NULL,
    [UllagesF]               FLOAT (53)    NULL,
    [NewStoreF]              FLOAT (53)    NULL,
    [DcAllowF]               FLOAT (53)    NULL,
    [balListFee]             FLOAT (53)    NULL,
    [balCDF]                 FLOAT (53)    NULL,
    [balFixedTT]             FLOAT (53)    NULL,
    [balFixedTTGL]           FLOAT (53)    NULL,
    [balFixedTTGLTwo]        FLOAT (53)    NULL,
    [importlogID]            INT           NOT NULL
);

